name: System Tests

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '**'
      - '!**.md'
      - '!**.png'
  push:
    branches: [ "main" ]
    paths:
      - '**'
      - '!**.md'
      - '!**.png'
  workflow_dispatch:

env:
  GOVER: 1.17.2

jobs:
  b2b-raw-traffic:
    name: B2B raw traffic test
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./test/otg-examples/docker-compose/b2b
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}
      - name: Build otgen
        run: cd ../../../.. && go get && go mod tidy && go build && sudo mv otgen /usr/local/bin/otgen
      - name: Setup testbed
        run:  make install network deploy
      - name: Test1 RUN with STDIN YAML
        run:  cat otg.yml | otgen --log debug run -k
      - name: Test2 RUN with --api
        run:  cat otg.yml | otgen --log debug run -k --api https://127.0.0.1
      - name: Test3 RUN with --file --yaml
        run:  otgen --log debug run -k --file otg.yml --yaml
      - name: Test4 RUN with --interval
        run:  otgen --log debug run -k --file otg.yml --interval 2s
      - name: Test5 RUN with --metrics flow
        run:  otgen --log debug run -k --file otg.yml --metrics flow
      - name: Test6 RUN with --xeta 1.5
        run:  otgen --log debug run -k --file otg.yml --xeta 1.5
      - name: Cleanup
        run:  make clean
