name: System Test

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '**'
      - '!**.md'
      - '!**.png'
  workflow_dispatch:

env:
  GOVER: 1.17.2

jobs:
  b2b-raw-traffic:
    name: B2B raw traffic test
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./test/otg-examples/docker-compose/b2b
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}
      - name: Build otgen
        run: cd ../../../.. && go get && go mod tidy && go build && sudo mv otgen /usr/local/bin/otgen
      - name: Setup testbed
        run:  make install network deploy
      - name: Test1 "cat otg.yml | otgen run -k"
        run:  cat otg.yml | otgen --log debug run -k
      - name: Cleanup
        run:  make clean
