name: Unit Tests

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '**'
      - '!**.md'
      - '!**.png'
  push:
    branches: [ "main" ]
    paths:
      - '**'
      - '!**.md'
      - '!**.png'
  workflow_dispatch:

env:
  GOVER: 1.24

jobs:
  make-tests:
    name: Make tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: 'true'
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GOVER }}
      - name: Build
        run: make get build
      - name: Tests
        run:  make tests